### ISSUE TITLE
Initial Github Setup

### ISSUE THREAD

**Issue by sfhelmet** [Lukateki/LinkedOut-SOEN341Project2023#1]
# Add name and email on Readme.md
![image](https://user-images.githubusercontent.com/30945652/214535146-8523cbfb-e816-4412-9440-95ef91f7040c.png)

# Clone Repository into local setup

**Click on " <> Code" and copy the link**
![image](https://user-images.githubusercontent.com/30945652/214534700-3c4e8916-456b-4614-b685-2a95ec6c1d17.png)

**Paste link in your favorite ide's terminal and it should look like this:**

![image](https://user-images.githubusercontent.com/30945652/214534999-bdaffd74-64c8-4f78-85a5-d36ee598519f.png)

**Comment by heyitsarthur** [comment]
We should also add our Github user name and Role in the Readme.

**Comment by sfhelmet** [comment]
Thats a good idea!
